#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Rogelio Lozano. Rogelio Emmanuel Lozano Aranda.'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # I believe how you deal with what you don’t know is the most important to solve a problem. 
  
  Hi, I'm Rogelio Lozano. I have a bachelor's degree in physics and my professional interest is in data analytics and programming. I'm deeply interested in how to deal with uncertainty and complex problems. On this site, you can find some of the projects I've worked on and articles about things I think could be interesting/useful for people with similar interests.
  
contact: >
  # Contact

  Please, feel free to contact me [through my email](mailto:rogelio.aeloz@gmail.com) or [tweet at me](https://twitter.com/intent/tweet?text=%40RleLozano) if you have any questions.

#-------------------------------
# Work Section

projects:
- {name: 'Time series, network clustering', folder: 'proj+', file: 'projects/proj_timeseries_network.html'}
- {name: 'Covid-19-arcgis pro simulated', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Multiple regression examples', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Time series forecasting', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Statistical relationship comparisons', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/RleLozano'}
#- {icon: 'instagram', link: '#'}
- {icon: 'github', link: 'https://github.com/RogelioLozano'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/rogelio-emmanuel-lozano-aranda/'}
- {icon: 'envelope', link: 'mailto:rogelio.aeloz@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
